
name: zoom
version: latest
summary: video chat
description: |Zoom is a remote video conferencing application.

grade: stable 
confinement: classic
base: core18

architectures:
  - build-on: amd64

apps:
  zoom:
    command: bin/desktop-launch $SNAP/bin/Zoom
    environment:
      LD_LIBRARY_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$LD_LIBRARY_PATH"

parts:
  zoom:
    after: [desktop-glib-only]
    plugin: dump
    source-type: deb
    source:
      - on amd64: https://zoom.us/client/$SNAPCRAFT_PROJECT_VERSION/zoom_amd64.deb
     
    stage-packages:
      libglib2.0-0
      libgstreamer-plugins-base0.10-0 
      libxcb-shape0
      libxcb-shm0
      libxcb-xfixes0
      libxcb-randr0
      libxcb-image0
      libfontconfig1
      libgl1-mesa-glx
      libxi6
      libsm6
      libxrender1
      libpulse0
      libxcomposite1
      libxslt1.1
      libsqlite3-0
      libxcb-keysyms1
      libxcb-xtest0
    organize:
      'Zoom_v*': 'bin/Zoom'
